# scripts/dbt/dbt_project.yml
name: 'inventory_visibility'
version: '1.0'
profile: 'inventory_visibility'
config-version: 2

model-paths: ["models"]
seed-paths: ["seeds"]
test-paths: ["tests"]
macro-paths: ["macros"]

seeds:
  inventory_visibility:
    +schema: bronze

models:
  inventory_visibility:
    bronze:
      +schema: bronze
      +materialized: view
    silver:
      +schema: silver
      +materialized: table
    gold:
      +schema: gold
      +materialized: table
    monitoring:
      +schema: monitoring           # <- stable place for observability
      +materialized: table
