logistics_demo:
  outputs:
    prod:
      type: snowflake
      account: "{{ env_var('SNOWFLAKE_ACCOUNT') }}"
      user: "{{ env_var('SNOWFLAKE_USER') }}"
      authenticator: "{{ env_var('SNOWFLAKE_AUTHENTICATOR', 'PROGRAMMATIC_ACCESS_TOKEN') }}"
      token: "{{ env_var('SNOWFLAKE_TOKEN') }}"
      role: "{{ env_var('SNOWFLAKE_ROLE') }}"
      warehouse: "{{ env_var('SNOWFLAKE_WAREHOUSE') }}"
      database: "{{ env_var('SNOWFLAKE_DATABASE') }}"
      # Use dynamic schema name for production. If DBT_TARGET_SCHEMA is not set,
      # fall back to 'prod'.
      schema: "{{ env_var('DBT_TARGET_SCHEMA', 'prod') }}"
      threads: 4

    dev:
      type: snowflake
      account: "{{ env_var('SNOWFLAKE_ACCOUNT') }}"
      user: "{{ env_var('SNOWFLAKE_USER') }}"
      authenticator: "{{ env_var('SNOWFLAKE_AUTHENTICATOR', 'PROGRAMMATIC_ACCESS_TOKEN') }}"
      token: "{{ env_var('SNOWFLAKE_TOKEN') }}"
      role: "{{ env_var('SNOWFLAKE_ROLE') }}"
      warehouse: "{{ env_var('SNOWFLAKE_WAREHOUSE') }}"
      database: "{{ env_var('SNOWFLAKE_DATABASE') }}"
      # Use dynamic schema name for development. Default to 'dev' if not set.
      schema: "{{ env_var('DBT_TARGET_SCHEMA', 'dev') }}"
      threads: 4

    ci_cd:
      type: snowflake
      account: "{{ env_var('SNOWFLAKE_ACCOUNT') }}"
      user: "{{ env_var('SNOWFLAKE_USER') }}"
      authenticator: "{{ env_var('SNOWFLAKE_AUTHENTICATOR', 'PROGRAMMATIC_ACCESS_TOKEN') }}"
      token: "{{ env_var('SNOWFLAKE_TOKEN') }}"
      role: "{{ env_var('SNOWFLAKE_ROLE') }}"
      warehouse: "{{ env_var('SNOWFLAKE_WAREHOUSE') }}"
      database: "{{ env_var('SNOWFLAKE_DATABASE') }}"
      # CI/CD uses the dynamic DBT_TARGET_SCHEMA set by the orchestrator (e.g., ci_<run_id>)
      schema: "{{ env_var('DBT_TARGET_SCHEMA', 'default') }}"
      threads: 4

  # DBT_ENVIRONMENT should be set to 'prod', 'dev' or 'ci_cd' to select the target above.
  target: "{{ env_var('DBT_ENVIRONMENT', 'ci_cd') }}"
