name: 🧹 Inventory Cleanup Request
description: Request deletion of a Snowflake schema/object tied to an inventory feed/model
title: "[Cleanup]: <inventory-object-or-schema-name>"

labels: ["cleanup", "dbt", "snowflake"]

body:
  - type: input
    id: object_name
    attributes:
      label: "Schema/Object Name to Delete"
      description: "Specify the exact schema or object to be deleted (e.g., deprecated feed or isolated schema)."
      placeholder: "inv_supplier_stage_issue_123"
    validations:
      required: true

  - type: dropdown
    id: object_type
    attributes:
      label: "Object Type"
      options:
        - Schema
        - Table
        - View
        - Other
    validations:
      required: true

  - type: textarea
    id: reason
    attributes:
      label: "Reason for Deletion"
      description: "Clearly describe why this schema/object is obsolete."
    validations:
      required: true
