name: 🚀 Inventory Feed/Model Request
description: Request creation of a new inventory feed, staging object, or model in Snowflake/dbt
title: "[Feature]: <inventory-feed-or-model>"

labels: ["feature", "dbt", "snowflake"]

body:
  - type: input
    id: schema_name
    attributes:
      label: "Schema/Object Name"
      description: "Provide the desired name for the schema/object (useful for isolated schemas)."
      placeholder: "inv_supplier_stage"
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: "Inventory Use Case"
      description: "Describe the feed or model (POS/ERP/WMS/e-comm/supplier), desired latency (batch/streaming), and stock metrics needed."
    validations:
      required: true

  - type: dropdown
    id: object_type
    attributes:
      label: "Object Type"
      options:
        - Schema
        - Table
        - View
        - Other
    validations:
      required: true
