-- Values are injected from the environment (e.g., via envsubst in CI).
SET WAREHOUSE_NAME = '${SNOWFLAKE_WAREHOUSE}';
SET DATABASE_NAME = '${SNOWFLAKE_DATABASE}';
SET ROLE_NAME = '${SNOWFLAKE_ROLE}';
SET USER_NAME = '${SNOWFLAKE_USER}';
SET USER_PASSWORD = '${SNOWFLAKE_USER_PASSWORD}'; -- pragma: allowlist secret (placeholder only)
SET PUBLIC_SCHEMA = $DATABASE_NAME || '.PUBLIC';
SET MONITORING_SCHEMA = $DATABASE_NAME || '.MONITORING';

CREATE OR REPLACE WAREHOUSE IDENTIFIER($WAREHOUSE_NAME)
    WAREHOUSE_SIZE = 'XSMALL'
    AUTO_SUSPEND = 300
    AUTO_RESUME = TRUE
    MIN_CLUSTER_COUNT = 1
    MAX_CLUSTER_COUNT = 1
    INITIALLY_SUSPENDED = TRUE
    COMMENT = 'Warehouse for our demo lab.';
CREATE DATABASE IF NOT EXISTS IDENTIFIER($DATABASE_NAME) COMMENT = 'Database for DataOps Course';
CREATE ROLE IF NOT EXISTS IDENTIFIER($ROLE_NAME) COMMENT = 'Role for data analysts to view and query data.';
GRANT USAGE ON WAREHOUSE IDENTIFIER($WAREHOUSE_NAME) TO ROLE IDENTIFIER($ROLE_NAME);
GRANT OPERATE ON WAREHOUSE IDENTIFIER($WAREHOUSE_NAME) TO ROLE IDENTIFIER($ROLE_NAME);
GRANT USAGE ON DATABASE IDENTIFIER($DATABASE_NAME) TO ROLE IDENTIFIER($ROLE_NAME);
GRANT CREATE SCHEMA ON DATABASE IDENTIFIER($DATABASE_NAME) TO ROLE IDENTIFIER($ROLE_NAME);
GRANT USAGE ON ALL SCHEMAS IN DATABASE IDENTIFIER($DATABASE_NAME) TO ROLE IDENTIFIER($ROLE_NAME);
GRANT USAGE ON FUTURE SCHEMAS IN DATABASE IDENTIFIER($DATABASE_NAME) TO ROLE IDENTIFIER($ROLE_NAME);
GRANT SELECT ON ALL TABLES IN SCHEMA IDENTIFIER($PUBLIC_SCHEMA) TO ROLE IDENTIFIER($ROLE_NAME);
GRANT SELECT ON FUTURE TABLES IN SCHEMA IDENTIFIER($PUBLIC_SCHEMA) TO ROLE IDENTIFIER($ROLE_NAME);
CREATE USER IF NOT EXISTS IDENTIFIER($USER_NAME)
    PASSWORD=$USER_PASSWORD
    DEFAULT_WAREHOUSE=IDENTIFIER($WAREHOUSE_NAME)
    DEFAULT_ROLE=IDENTIFIER($ROLE_NAME);
GRANT ROLE IDENTIFIER($ROLE_NAME) TO USER IDENTIFIER($USER_NAME);

CREATE SCHEMA IF NOT EXISTS IDENTIFIER($MONITORING_SCHEMA) COMMENT = 'Schema for observability metrics.';
GRANT USAGE ON SCHEMA IDENTIFIER($MONITORING_SCHEMA) TO ROLE IDENTIFIER($ROLE_NAME);
GRANT ALL PRIVILEGES ON SCHEMA IDENTIFIER($MONITORING_SCHEMA) TO ROLE IDENTIFIER($ROLE_NAME);
GRANT SELECT ON ALL TABLES IN SCHEMA IDENTIFIER($MONITORING_SCHEMA) TO ROLE IDENTIFIER($ROLE_NAME);
GRANT SELECT ON FUTURE TABLES IN SCHEMA IDENTIFIER($MONITORING_SCHEMA) TO ROLE IDENTIFIER($ROLE_NAME);
GRANT SELECT ON ALL VIEWS IN SCHEMA IDENTIFIER($MONITORING_SCHEMA) TO ROLE IDENTIFIER($ROLE_NAME);
GRANT SELECT ON FUTURE VIEWS IN SCHEMA IDENTIFIER($MONITORING_SCHEMA) TO ROLE IDENTIFIER($ROLE_NAME);
